name: Docker Image CI

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Latest Version
        id: get-latest-version
        run: echo "::set-output name=LATEST_KUBERNETES_VERSION::`curl -L -s https://dl.k8s.io/release/stable.txt`"
      - name: Get Output Version
        run: echo "The latest version is ${{ steps.get-latest-version.outputs.LATEST_KUBERNETES_VERSION }}"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            KUBERNETES_RELEASE=${{ steps.get-latest-version.outputs.LATEST_KUBERNETES_VERSION }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/kubectl:${{ steps.get-latest-version.outputs.LATEST_KUBERNETES_VERSION }}
            ${{ secrets.DOCKERHUB_USERNAME }}/kubectl:latest